### ISSUE TITLE
Unable to install ChIA-PET2 in Ubuntu 15.10

### ISSUE THREAD

**Issue by chadi-elfarran** [GuipengLi/ChIA-PET2#1]
Dear admin,

Thank you for creating this tool. I was able to install this tool easily in a system having Fedora OS.

However when I tried installing it in a system with an Ubuntu 15.10, the installation fails.

The following messages appear in the terminal:

"g++ -Wall -O2 -Wno-char-subscripts -lz -fopenmp -o /home/chadiak/Apps/ChIA-PET2/bin/trimLinker /home/chadiak/Apps/ChIA-PET2/src/trimLinker.cpp
/tmp/cct7x7hm.o: In function `read_fastq(gzFile_s*&, int)':
trimLinker.cpp:(.text+0x44bc): undefined reference to`gzgets'
trimLinker.cpp:(.text+0x44cd): undefined reference to `gzgets'
trimLinker.cpp:(.text+0x45aa): undefined reference to`gzgets'
trimLinker.cpp:(.text+0x45f3): undefined reference to `gzgets'
/tmp/cct7x7hm.o: In function`parseFastqgz_p(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
trimLinker.cpp:(.text+0x483b): undefined reference to `gzopen'
trimLinker.cpp:(.text+0x484e): undefined reference to`gzopen'
trimLinker.cpp:(.text+0x4cc7): undefined reference to `gzclose'
trimLinker.cpp:(.text+0x4cd1): undefined reference to`gzclose'
/tmp/cct7x7hm.o: In function `parseFastqBridgegz_p(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
trimLinker.cpp:(.text+0x527b): undefined reference to`gzopen'
trimLinker.cpp:(.text+0x528e): undefined reference to `gzopen'
trimLinker.cpp:(.text+0x5707): undefined reference to`gzclose'
trimLinker.cpp:(.text+0x5711): undefined reference to `gzclose'
/tmp/cct7x7hm.o: In function`parseFastqEnzymegz_p(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
trimLinker.cpp:(.text+0x5d0e): undefined reference to `gzopen'
trimLinker.cpp:(.text+0x5d21): undefined reference to`gzopen'
trimLinker.cpp:(.text+0x6187): undefined reference to `gzclose'
trimLinker.cpp:(.text+0x6191): undefined reference to`gzclose'
/tmp/cct7x7hm.o: In function `parseFastqgz(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
trimLinker.cpp:(.text+0x7c6a): undefined reference to`gzopen'
trimLinker.cpp:(.text+0x7c7d): undefined reference to `gzopen'
trimLinker.cpp:(.text+0x7e6e): undefined reference to`gzgets'
trimLinker.cpp:(.text+0x7eb3): undefined reference to `gzgets'
/tmp/cct7x7hm.o: In function`parseFastqBridgegz(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
trimLinker.cpp:(.text+0x8fea): undefined reference to `gzopen'
trimLinker.cpp:(.text+0x8ffd): undefined reference to`gzopen'
trimLinker.cpp:(.text+0x91ee): undefined reference to `gzgets'
trimLinker.cpp:(.text+0x9233): undefined reference to`gzgets'
/tmp/cct7x7hm.o: In function `parseFastqEnzymegz(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
trimLinker.cpp:(.text+0xafd5): undefined reference to`gzopen'
trimLinker.cpp:(.text+0xafe8): undefined reference to `gzopen'
trimLinker.cpp:(.text+0xb1c6): undefined reference to`gzgets'
trimLinker.cpp:(.text+0xb206): undefined reference to `gzgets'
collect2: error: ld returned 1 exit status
Makefile:42: recipe for target 'trimLinker' failed
make: **\* [trimLinker] Error 1"

Can you kindly assist in rectifying the above mentioned issue?

Best Wishes

**Comment by GuipengLi** [comment]
Thank you for pointing this out.
It seems like that the zlib.h was not found. Is zlib installed in the system?

**Comment by chadi-elfarran** [comment]
Hi Guipeng, 

Yes it is installed. I have just fixed the problem by modifying the Makefile code as follows:

Added the follwing as Line 20:
LDFLAGS = -lz

And changing the compilation codes to the following:

"## Build C++ code
trimLinker: $(SOURCES)/trimLinker.cpp
    $(CC) $(CFLAGS) -o ${BIN}/$@ ${SOURCES}/trimLinker.cpp $(LDFLAGS)

buildBedpe: $(SOURCES)/buildBedpe.cpp
    $(CC) $(CFLAGS) -o ${BIN}/$@ ${SOURCES}/buildBedpe.cpp $(LDFLAGS)

removeDup: $(SOURCES)/removeDup.cpp
    $(CC) $(CFLAGS) -o ${BIN}/$@ ${SOURCES}/removeDup.cpp $(LDFLAGS)

buildTagAlign: $(SOURCES)/buildTagAlign.cpp
    $(CC) $(CFLAGS) -o ${BIN}/$@ ${SOURCES}/buildTagAlign.cpp $(LDFLAGS)

tag2Depth: $(SOURCES)/tag2Depth.cpp
    $(CC) $(CFLAGS) -o ${BIN}/$@ ${SOURCES}/tag2Depth.cpp $(LDFLAGS)

bedpe2Interaction: $(SOURCES)/bedpe2Interaction.cpp
    $(CC) $(CFLAGS) -o ${BIN}/$@ ${SOURCES}/bedpe2Interaction.cpp $(LDFLAGS)

bedpe2Phased: $(SOURCES)/bedpe2Phased.cpp
    $(CC) $(CFLAGS) -o ${BIN}/$@ ${SOURCES}/bedpe2Phased.cpp $(LDFLAGS)

bedpe2Matrix: $(SOURCES)/bedpe2Matrix.cpp
    $(CC) -Wall -O2 -std=c++0x -o ${BIN}/$@ ${SOURCES}/bedpe2Matrix.cpp $(LDFLAGS)"

Seems to be working fine now. Not sure why this is required for Ubuntu but it seems the "-lz" has to be at the end of each command.

Best Wishes,

**Comment by GuipengLi** [comment]
Great! Thank you.
