### ISSUE TITLE
 Download ChIA-PET2.tar.gz  Url

### ISSUE THREAD

**Issue by tatafu** [GuipengLi/ChIA-PET2#12]
hello, before operate this step :tar -zxvf ChIA-PET2.tar.gz ,we should first download this resource, in my linux server ,please note the download url to get the  ChIA-PET2.tar.gz file.
thanks

**Comment by tatafu** [comment]
I download from code tab,  the download resource name is not ChIA-PET2.tar.gz

**Comment by GuipengLi** [comment]
It's betterr to use the newest one.

git clone https://github.com/GuipengLi/ChIA-PET2.git

**Comment by tatafu** [comment]
I think you didn't  see clear my question （I use the latest one） , before I decompose ChIA-PET2.tar.gz ,how could I  download the Archive。

**Comment by GuipengLi** [comment]
wget https://github.com/GuipengLi/ChIA-PET2/archive/v0.9.3.tar.gz

**Comment by tatafu** [comment]
thanks, it's works
