### ISSUE TITLE
enough confident interactions to learn the model

### ISSUE THREAD

**Issue by rayezh** [GuipengLi/ChIA-PET2#13]
Hi, Guipeng,
     I'm trying to call interactions on this dataset from encode: https://www.encodeproject.org/experiments/ENCSR000BZX/
  Since I saw people in previous posts had the same problem I checked my data, tried a few times and used the command as follows: 
`ChIA-PET2 -g ./BWAIndex/genome.fa -b ./human.hg19.genome  -f HCT116_POL2_r1.fastq -r HCT116_POL2_r2.fastq -o ./ChIA-PET2 -n ChIA-PET2_HCT116_POL2 -d 1 -Q 20 
`
And this is what I got from step 7:

> Loading required package: VGAM
> Loading required package: methods
> Loading required package: stats4
> Loading required package: splines
> Running MICC...
> Intra data:  ./ChIA-PET2_HCT116_POL2.interactions.intra.bedpe 
> Inter data:  ./ChIA-PET2_HCT116_POL2.interactions.inter.bedpe 
> Output file:  ./HCT116_POL2_interactions.out 
> PET count cutoff:  2 
> Minimun Confident PET count:  5 
> reltol:  1e-08 
> Loading intra data...
> Loading inter data...
> Cacluating...
> Intra:  1083 	Inter: 9184 
> Error: Don't have enough confident interactions to learn the model.
> Execution halted
> 

the QC plot is like this. 
[ChIA-PET2_HCT116_POL2.QCplot.pdf](https://github.com/GuipengLi/ChIA-PET2/files/1933631/ChIA-PET2_HCT116_POL2.QCplot.pdf)
The interchromosomal interaction portion is relatively high, while I'm not sure if this is the problem. Could you help me on that? Thanks!

Rayezh

**Comment by GuipengLi** [comment]
Hi Rayezh,

The command you used seems appropriate to me. From the QC plot, I'm not sure whether the quality of this dataset is good enough to do sequential analysis. You probably notice that the duplicate rate is very high and the inter/intra ratio is also high. What's the karyotype of this cell line? If there are many chromosome structure variations, the interchromosomal portion will be high.

Or do you find any published paper that used this dataset ?

Guipeng

**Comment by rayezh** [comment]
Actually this dataset was published in this paper:
[Extensive Promoter-Centered Chromatin Interactions Provide a Topological Basis for Transcription Regulation](https://www.sciencedirect.com/science/article/pii/S0092867411015170?via%3Dihub)
the karyotype was normal as diploid as they discribed and they used ChIA-PET Tool to call the peaks although the specific process was not described very much detailed in the paper. I'm trying to replicated their peak calling procedure but failed.
I wonder if there're some critical differeces between CPT and CPT2 that might be overlooked?

**Comment by rayezh** [comment]
And I just checked their processed interactions uploaded in ENCODE(https://www.encodeproject.org/files/ENCFF001THT/) and found their interactions are indeed mostly interchromosome and only a small fraction of them are intrachromosome(605/10762). It should be their data's problem. 

Thanks for your help!
