### ISSUE TITLE
stopped at 4th stage

### ISSUE THREAD

**Issue by rayezh** [GuipengLi/ChIA-PET2#14]
Hi Guipeng,
  I'm running ChIA-PET2 on the bridge-linker experiment and it stopped at stage 5 psort without warning. my command was like this:
    
` ChIA-PET2 -t 8 -g /espresso/share/genomes/hg19/Sequence/BWAIndex/genome.fa -b /opt/apps/rhel6/bedtools/2.25.0/genomes/human.hg19.genome  -f SYN_HepG2_RAD21_r1.fastq -r SYN_HepG2_RAD21_r2.fastq -o ./ChIA-PET2 -n ChIA-PET2_HepG2_RAD21 -k 2 -m 1`

and the pipeline just stopped here:

> [04-24 12:03:19] Running Step 5: Detect Interactions ...

extendpeak ./ChIA-PET2/ChIA-PET2_HepG2_RAD21_peaks.narrowPeak 500 ./ChIA-PET2/ChIA-PET2_HepG2_RAD21_peaks.slopPeak
Running  extendpeak...
bedtools slop -i ./ChIA-PET2/ChIA-PET2_HepG2_RAD21_peaks.narrowPeak -g /opt/apps/rhel6/bedtools/2.25.0/genomes/human.hg19.genome -b 500 | bedtools merge -d 256 > ./ChIA-PET2/ChIA-PET2_HepG2_RAD21_peaks.slopPeak
awk 'BEGIN{OFS="\t";i=1}{print $1,$2,$3,"peak_"i;i=i+1}' ./ChIA-PET2/ChIA-PET2_HepG2_RAD21_peaks.slopPeak > tmp.bed; mv tmp.bed ./ChIA-PET2/ChIA-PET2_HepG2_RAD21_peaks.slopPeak
peak_depth2 ./ChIA-PET2/ChIA-PET2_HepG2_RAD21.rmdup.bedpe.tag 100 ./ChIA-PET2/ChIA-PET2_HepG2_RAD21_peaks.slopPeak ./ChIA-PET2/ChIA-PET2_HepG2_RAD21.peaks.depth
Running peakdepth...
psort ./ChIA-PET2/ChIA-PET2_HepG2_RAD21.rmdup.bedpe.tag ./ChIA-PET2/ChIA-PET2_HepG2_RAD21.rmdup.bedpe.tag.sorted > /dev/null 2>&1

  
the bedpe file was empty. it seems the split sorted file failed to cat into one. Do you know how to fix that?
Thank you!
Raye

**Comment by rayezh** [comment]
sorry I have to correct the title that stopped at stage 5

**Comment by GuipengLi** [comment]
This bug may be a bug of psort in utils file. Could you try to replace the 107th line "cmdsort="psort $tagfile $tagfile.sorted > /dev/null 2>&1"" in utils file to "cmdsort="sort -k1,1 -k2,2n --parallel=8 $tagfile > $tagfile.sorted" ?

This require your system has GNU sort installed.

**Comment by rayezh** [comment]
Thanks! That worked smoothly.
