### ISSUE TITLE
extend parameter not used?

### ISSUE THREAD

**Issue by rakarnik** [GuipengLi/ChIA-PET2#16]
Hi,
I am trying to read through the ChIA-PET2 code to re-implement the algorithm in our own pipeline. I had a question about the extend parameter: the current code seems to use "peak_depth2" in bin/utils, which does not extend the reads before doing the coverageBed call. Is my reading of the code correct? Is the read extension only needed for short read data?

**Comment by GuipengLi** [comment]
Hi,
You are right. Because the peaks have been extended, so it does not need to extend the short/long reads again.

**Comment by rakarnik** [comment]
Thanks Guipeng!
