### ISSUE TITLE
How can we get the significant Interactions?

### ISSUE THREAD

**Issue by MamushChu** [GuipengLi/ChIA-PET2#22]
I am analyzing K562 and MCF7 using ChIA-PET2 tools using the following script 
`ChIA-PET2 -g ~/data/reference/hg19.fa -b ~/data/human.hg19.genome/hg19.chrom.sizes.txt -f ~/data/MCF7/MCF7_1.fastq -r ~/data/MCF7/MCF7_2.fastq  -o ~/results/ChIA-PET2/MCF7/ -n MCF7 -d 1`

I  got the MCF7.interactions.MICC and K562.interactions.MICC and then after,  I filter the significant interaction with FDR < 0.05 and got the following output
```
- wc -l MCF7.interactions.MICC = 9451
- awk '($13 < 0.05)' MCF7.interactions.MICC | wc -l = 0 
- wc -l K562.interactions.MICC = 15222
- awk '($13 < 0.05)' K562.interactions.MICC | wc -l = 4733
``` 
I am confused on the MCF7 data set that how all  interaction are not significant. Therefore, would you please give some hint about how we get the significant interaction using your tool or can we consider all the loops inside .MICC file as significant interactions.

**Comment by GuipengLi** [comment]
Which version of ChIA-PET2 do you use? version 0.9.3 was updated to set default parameters for ultra deep sequencing data to call significant interactions. You may try the below command. It will be great if you could send me some feeback.

Rscript path_to/MICC2.R interactions.intra.bedpe interactions.inter.bedpe miccOUT 1 5 1e-3

**Comment by MamushChu** [comment]
Thank you Dear GuipengLi for your quick response. 

I tried it and got 35,528 and 39,515 significant interaction in MCF7 and K562 respectively. But it is too much as I compared to other tools; even too much as  ChIA-PET tools (It may not be, as far as I know). 

FYI: The raw read data was downloaded from ENA with run accession numbers SRR372747, SRR372748 (two K562 replicates), SRR372741 and SRR372742 (two MCF7 replicates). Then, the two replicates for each cell line are combined into a single experiment.

**Comment by GuipengLi** [comment]
I would suggest using additional criteria to control the false positves, e.g.  the number of supported reads should be at least 2.

**Comment by MamushChu** [comment]
I was using version 0.9.3 and now, I switched to version 0.9.2 using the following script

 `ChIA-PET2 -g ~/data/reference/hg19.fa -b ~/data/human.hg19.genome/hg19.chrom.sizes.txt -f ~/data/MCF7/MCF7_1.fastq -r ~/data/MCF7/MCF7_2.fastq -A GTTGGATAAG -B GTTGGAATGT -o ~/results/ChIA-PET2/MCF7/ -n MCF7 -m 0 -e 0 -k 0 -d 1 -Q 20 -C 2` 
 
and got 6559 and 14441 significant interaction for MCF7 and K562 respectively. This seems ok. 

Thank you for your help again!!!
