### ISSUE TITLE
bedpe2Interaction core dumped

### ISSUE THREAD

**Issue by hugch2020** [GuipengLi/ChIA-PET2#30]
Hi @GuipengLi ,
An error was reported when I run bedpe2Interaction.

bedpe2Interaction RAD21_ChIAPET.rmdup.bedpe.tmp RAD21_ChIAPET.interactions RAD21_ChIAPET.stat
Running bedpe2Interaction...
Segmentation fault (core dumped)

The input file format is as follows,
head RAD21_ChIAPET.rmdup.bedpe.tmp
chrX    38634826        38634927        chrX    38634869        38634970        SRR8659342.732269       .       +       -       chrX    38633862        38635745        553
chrX    38634826        38634927        chrX    38634869        38634970        SRR8659342.732269       .       +       -       chrX    38633862        38635745        553
chrX    36866684        36866785        chrX    36866967        36867066        SRR8659342.4394649      .       +       -       chrX    36866138        36868189        237
chrX    36866684        36866785        chrX    36866967        36867066        SRR8659342.4394649      .       +       -       chrX    36866138        36868189        237
chr15   77107681        77107782        chr15   77107755        77107797        SRR8659342.2501571      .       +       -       chr15   77106748        77108892        996
chr15   77107681        77107782        chr15   77107755        77107797        SRR8659342.2501571      .       +       -       chr15   77106748        77108892        996
chrX    37059730        37059831        chrX    37059852        37059953        SRR8659342.3183715      .       +       -       chrX    37059546        37061952        380
chrX    37059730        37059831        chrX    37059852        37059953        SRR8659342.3183715      .       +       -       chrX    37059546        37061952        380
chr15   74373832        74373933        chr15   74373935        74374036        SRR8659342.8464568      .       +       -       chr15   74372747        74376257        3104
chr15   74373832        74373933        chr15   74373935        74374036        SRR8659342.8464568      .       +       -       chr15   74372747        74376257        3104

I have no idea where the problem is, could you give me some advice. Thanks so much!

**Comment by GuipengLi** [comment]
How did you generated this file RAD21_ChIAPET.rmdup.bedpe.tmp ?
bedpe2Interaction is used internally within ChIA-PET2. The input file format should be correct.

**Comment by hugch2020** [comment]
You're right. I found that I didn't add peak name after bedSlop, so the format of bedpe.tmp is not correct. Thanks!
