### ISSUE TITLE
BWA alignment issue

### ISSUE THREAD

**Issue by zentnerlab** [GuipengLi/ChIA-PET2#6]
I'm running into what seems to be an issue with the BWA alignment. The linker trimming goes fine, but the alignment spits out header-only SAM files that lead to buildBedpe crashing. I'm using BWA 0.7.15. The output/error log is attached. Thanks for any help!

[ChIA-PET2_test_OE.txt](https://github.com/GuipengLi/ChIA-PET2/files/966471/ChIA-PET2_test_OE.txt)

**Comment by GuipengLi** [comment]
If the reads are short, e.g. ~20bp, please use "-d 1" option for short reads.

**Comment by zentnerlab** [comment]
Yes, that took care of it. Thank you!
