### ISSUE TITLE
'm' parameter of this tool

### ISSUE THREAD

**Issue by gunjangala** [GuipengLi/ChIA-PET2#8]
Hello Guipeng Li,
Quick question: If m is set to 2, what sequence to put in for A and B? Are we required to set those parameters or is there a way to set them off?

Thanks,
Gunjan

**Comment by GuipengLi** [comment]
Hi Gunjan,

We keep this option (-m 2) only for experimental usage. A and B parameters are set based on what enzyme is used and how the DNA fragments are ligated. For example, HindIII cuts the following sequence

5'... A|AGCTT...3'
3'... TTCGA|A...5'

If the protocol fills the sticky ends and ligates them (like Hi-C), we will set "-A AGCTAGCT -B AGCTAGCT".

**Comment by gunjangala** [comment]
Ok. Thank you.
